"""Renderer — structured outputs in JSON, Markdown, and Rich CLI table."""

from __future__ import annotations

import json
from typing import Any

from rich.console import Console
from rich.markup import escape as rich_escape
from rich.table import Table


def render_json(issues: list[dict[str, Any]], indent: int = 2) -> str:
    """Return pretty-printed JSON string of issues."""
    return json.dumps(issues, indent=indent, default=str)


def render_markdown(issues: list[dict[str, Any]]) -> str:
    """Render issues as a Markdown report grouped by project."""
    from taskforge.queries import group_by_project

    groups = group_by_project(issues)
    lines: list[str] = ["# TaskForge — Issue Report", ""]

    for project, proj_issues in groups.items():
        lines.append(f"## {project}")
        lines.append("")
        lines.append("| Key | Type | Summary | Status | Priority | Due |")
        lines.append("|-----|------|---------|--------|----------|-----|")

        for issue in proj_issues:
            key = issue.get("key", "")
            itype = issue.get("type", "")
            summary = (issue.get("summary") or "")[:60]
            status = issue.get("status", "")
            priority = issue.get("priority", "")
            due = issue.get("dueDate") or "—"
            lines.append(f"| {key} | {itype} | {summary} | {status} | {priority} | {due} |")

        lines.append("")

    lines.append(f"*Generated by TaskForge — {len(issues)} issues total*")
    return "\n".join(lines)


def _safe(val: Any) -> str:
    """Safely convert a value to a string and escape Rich markup."""
    s = str(val) if val is not None else "—"
    return rich_escape(s)


def render_table(issues: list[dict[str, Any]], console: Console | None = None) -> None:
    """Print a Rich table of issues to the console."""
    con = console or Console()

    table = Table(
        title="TaskForge Issues",
        show_lines=True,
        header_style="bold cyan",
        border_style="dim",
    )

    table.add_column("Key", style="bold yellow", no_wrap=True)
    table.add_column("Type", style="dim")
    table.add_column("Summary", max_width=50)
    table.add_column("Status", style="green")
    table.add_column("Priority", style="magenta")
    table.add_column("Due", style="red")
    table.add_column("Assignee", style="blue")

    for issue in issues:
        status = _safe(issue.get("status", ""))
        status_style = ""
        cat = issue.get("statusCategory", "")
        if cat and cat.lower() == "done":
            status_style = "dim strike"
        elif cat and cat.lower() == "in progress":
            status_style = "bold green"

        status_cell = f"[{status_style}]{status}[/{status_style}]" if status_style else status

        table.add_row(
            _safe(issue.get("key", "")),
            _safe(issue.get("type", "")),
            rich_escape((issue.get("summary") or "")[:50]),
            status_cell,
            _safe(issue.get("priority", "")),
            _safe(issue.get("dueDate")),
            _safe(issue.get("assignee")),
        )

    con.print(table)


def render_blocked_table(
    blocked: list[dict[str, Any]], console: Console | None = None
) -> None:
    """Print a table of blocked issues with their blockers."""
    con = console or Console()

    table = Table(
        title="Blocked Issues",
        show_lines=True,
        header_style="bold red",
    )

    table.add_column("Issue", style="bold yellow", no_wrap=True)
    table.add_column("Summary", max_width=40)
    table.add_column("Blocked By", style="red")
    table.add_column("Blocker Status", style="dim")

    for item in blocked:
        issue = item["issue"]
        blockers = item["blockers"]
        blocker_keys = ", ".join(_safe(b.get("key") or "flag") for b in blockers)
        blocker_statuses = ", ".join(_safe(b.get("status") or "?") for b in blockers)

        table.add_row(
            _safe(issue.get("key", "")),
            rich_escape((issue.get("summary") or "")[:40]),
            blocker_keys,
            blocker_statuses,
        )

    con.print(table)


def render_ranked_table(
    ranked: list[dict[str, Any]], console: Console | None = None
) -> None:
    """Print ranking table with score breakdown."""
    con = console or Console()

    table = Table(
        title="Recommended Next Tasks",
        show_lines=True,
        header_style="bold green",
    )

    table.add_column("#", style="bold", width=3)
    table.add_column("Key", style="bold yellow", no_wrap=True)
    table.add_column("Summary", max_width=40)
    table.add_column("Score", style="bold cyan", justify="right")
    table.add_column("Priority", justify="right")
    table.add_column("Due", justify="right")
    table.add_column("Recency", justify="right")
    table.add_column("Blocked", justify="right")

    for idx, item in enumerate(ranked, 1):
        issue = item["issue"]
        bd = item["breakdown"]
        table.add_row(
            str(idx),
            _safe(issue.get("key", "")),
            rich_escape((issue.get("summary") or "")[:40]),
            str(item["score"]),
            str(bd["priority"]),
            str(bd["due_date"]),
            str(bd["recency"]),
            str(bd["blocked_penalty"]) if bd["blocked_penalty"] else "—",
        )

    con.print(table)
